### ISSUE TITLE
random ArgumentNullException in VS MEF when using VS

### ISSUE THREAD

**Issue by lifengl** [Microsoft/vs-mef#108]
It is a random problem reported by customers, and it has random stack in the product side (random place accessing MEF), but share the same stack similar to the one I pasted here.

After looking into the MEF code, I think it is a MEF code bug, independent to the composition.  The only explanation I can get is that the bug is inside RuntimeImport.IsLazy implementation.  It runs into a race condition, because Nullable<bool> is not thread safe.  When one thread computed the value and sets the value to true, in the split time, another thread can see the value has been set, and is false, which leads it to think valueFunction is null.

```
Microsoft.Requires.NotNull[T](T,String)
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportElement(RuntimePartLifecycleTracker,RuntimeImport,RuntimeExport,Func`3)
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.GetValueForImportSite(RuntimePartLifecycleTracker,RuntimeImport)
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.RuntimePartLifecycleTracker.SatisfyImports()
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.SatisfyImmediateImports()
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToStateTransitively(PartLifecycleState,HashSet`1)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveNext(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.MoveToState(PartLifecycleState)
Microsoft.VisualStudio.Composition.ExportProvider.PartLifecycleTracker.GetValueReadyToExpose()
Microsoft.VisualStudio.Composition.RuntimeExportProviderFactory.RuntimeExportProvider.<>c__DisplayClass15_0.<GetExportedValueHelper>b__0()
Microsoft.VisualStudio.Composition.DelegateServices.<>c__DisplayClass2_0`1.<As>b__0()
System.Lazy`1.CreateValue()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
```

**Comment by AArnott** [comment]
Thanks for the report and your investigation. Do you happen to have a heap dump from a repro? 

> independent to the composition

Do you mean that given one composition, the error may or may not repro, non-deterministically?

**Comment by AArnott** [comment]
We only hit the `Requires.NotNull` path if the `bool?` returns *true*, which is the non-default value. We may indeed have a race condition bug here, but I would expect the value to be its default `false` value in that case. When the value is `true`, we then test an argument against null, which couldn't be vulnerable to the race condition.

Looking more into this (and maybe this is what you meant in your investigation anyway), if the *caller* of the method hit the race condition, and at that point the `IsLazy` property returned false, then the lazyFactory would initialize to `null` instead of a non-null value, leading to a null argument being passed in. I'll see if I can repro that and prepare a fix.

**Comment by lifengl** [comment]
We don't have a dump file, but only the exception from loggings.

If we remove unrelated the code, the condensed logic looks like this:
```code
 if (import.valueFactory == null && import.IsLazy)
{
  import.valueFactory = methodInfo.CreateDelegate(...);
}

var valueFactory = import.valueFactory;
if (import.IsLazy)
{
  Require.NotNull(valueFactory, nameof(valueFactory); // This line throws the exception.
}
bool? isLazy;
bool IsLazy {
  get {
    if (!this.isLazy.HasValue) {
      this.isLazy = ComputeIsLazy();
    }
    return this.isLazy.Value;
 }
```

Based on this code, this.IsLazy must be true, when this happens. It is very unlikey methodInfo.CreateDelegate will return null here.  In that case, IsLazy must return false once, and return true later. IsLazy is actually computed in a lazy way.  It is still possible that IsLazy is computed twice in two threads, it is set to false in one thread, and true on another thread slightly later.  If that is the case, it will be a very ordinary race condition bug.  The implementation of IsLazy is only valid, when the computation logic is stable.  By looking into the code, it is very simple logic containing some culture insensitive string comparisons, and I could not explain what variation can lead it to produce different values.  The 3rd explanation will be that nullable<bool> actually contains two values, one flag, one value field, and setting the value is not an atomic operation.  When one thread sets the value from null to true, the other thread can pick up the flag and the false in the value field, before the first thread updates the value field.  So far, I think it is the most likely reason we run into those exceptions in the product.  We can easily change the code to use a 3 value enum value to fix the problem.

**Comment by drewnoakes** [comment]
Developer Community reports:
- https://developercommunity.visualstudio.com/content/problem/329106/value-cannot-be-null-parameter-name-lazyfactory.html
- https://developercommunity.visualstudio.com/content/problem/379006/lazy-factory-is-null-when-starting-studio-by-loadi.html

**Comment by AArnott** [comment]
>  The 3rd explanation will be that nullable actually contains two values, one flag, one value field, and setting the value is not an atomic operation. 

I agree that this is the most plausible explanation. And it's true that there are two fields and that writing is not atomic. But it's also true that [the code is written](https://source.dot.net/#System.Private.CoreLib/shared/System/Nullable.cs,99637d3d3d3a1bab) to assign the value first, then assign the hasValue field second, so if there is a torn state race condition, it would presumably be expressed as seeing that the lazy is not yet initialized, rather than that it is initialized to null. 
But that's assuming that instructions are not reordered. And I suspect this is one of those places where the CPU is technically allowed to reorder instructions for performance since there are no memory barriers in place (which locks would put in place).

> We can easily change the code to use a 3 value enum value to fix the problem.

True. That would avoid adding locks, which might be nice.

**Comment by AArnott** [comment]
Thanks, @drewnoakes. Your https://developercommunity.visualstudio.com/content/problem/379006/lazy-factory-is-null-when-starting-studio-by-loadi.html link is a different issue in CPS that has evidently already been fixed. But the first link is clearly a dupe of this one.
