### ISSUE TITLE
Documentation and samples

### ISSUE THREAD

**Issue by bradws** [Microsoft/vs-mef#119]
Hi,

I'm somewhat familiar with the old MEF 1 from years ago, and now wanting to use MEF for a standard 'plugins'-type scenario, and I prefer to use the latest ways.

I just wanted to know whether the demo at [AArnott/VSMefSample](https://github.com/AArnott/VSMefSample)  is still valid for me to study and learn (it's approx a year-and-a-half old now). Can you provide other modern examples, or is that good enough?

I'm mainly asking because I noticed the code in the Exported classes use the (now very old) `System.Composition` namespace, whereas others use the _vs-mef_ namespaces.

Thank-you.

**Comment by AArnott** [comment]
The sample you link to is still current. There are only two sets of MEF attributes. The oldest is `System.ComponentModel.Composition` and the newer one in `System.Composition`. VS-MEF does not define its own set of attributes (we thought 2 was enough :smile:). Either set are fine. My preference is `System.ComponentModel.Composition` since its default part creation policy is Shared. VS-MEF lets you mix and match attributes (but not within the same Part).

For this and more information, please review https://github.com/Microsoft/vs-mef/blob/master/doc/why.md and the docs it links to.
