### ISSUE TITLE
How to detect if cached composition data is obsolete?

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#144]
Let's say my main assembly has version `1.0.1.0`. I serialize its composition data to disk:

```c#
await cacheManager.SaveAsync(configuration, stream);
```

Then I update my assembly version to `1.0.2.0`. Finally, I successfully (and a bit unexpectedly) deserialize the composition data from the previously saved cache:

```c#
var epf = await cacheManager.LoadExportProviderFactoryAsync(stream, resolver);
```

I expected this to fail, since the version has changed. Viewing the serialized data, I can see the old version number lurking around. Running the application seems to work, but I guess there could have been a problem if the dependencies had changed.

Not sure how to interpret these findings. What is the expected behavior, and why?

More importantly, **is it possible to detect if a serialized cache is obsolete?**

**Comment by AArnott** [comment]
This vs-mef library does not address cache invalidation at all, at present. When we use this within Visual Studio itself, we have a great deal of code to handle cache invalidation. It's [something on our backlog](https://github.com/microsoft/vs-mef/projects/1) to someday rewrite that into this repo and make it a proper (and hopefully simpler) feature. 

The reason it worked for you when you loaded a stale cache is vs-mef has two modes: if the cache matches the assemblies exactly, it will use "fast reflection"; if the cache appears stale, it will failover silently to "slow reflection" and do the best it can with what you gave it. This means, as you suggest, that if you've made significant changes to the MEF graph itself, there could be runtime failures because no scanning of MEF parts occurs when you load a cache.

**Comment by znakeeye** [comment]
Thanks for your explanation.

In our case it would be good if we could force the cache loader to fail if the assemblies do _not_ match exactly. Is it possible to disable slow reflection, throwing an error instead?

**Comment by AArnott** [comment]
>  Is it possible to disable slow reflection, throwing an error instead?

You probably don't *really* want to do *that*. The feature to silently failover keeps your app from failing when Microsoft services Windows / .NET Framework assemblies via Windows Update. The MEF cache file includes metadata tokens from any assembly that is required in the graph, and that includes reference assemblies of the assemblies actually in the catalog. So if you have MEF assembly "a.dll", and it of course references mscorlib.dll, System.Runtime.dll, and/or netstandard.dll, then any time those reference assemblies change that can cause fast reflection to fail and slow reflection to automatically kick in. 

What I suspect you want is for the app to fail (or even better, the cache to be automatically refreshed) on startup of your app if any of the first-order MEF assemblies (the ones that actually define MEF parts) have changed. And that's what the cache invalidation code (that isn't offered yet by this repo) would do for you. It might even kick off a refresh in the background if slow reflection ever kicked in (for the reference assemblies) for better performance the next time. 

Is it possible for you to do this with vs-mef as is? Sure--after all VS does it today. But we don't rely on assembly version or even assembly file version, since those values don't change nearly as frequently as an assembly does in general. Instead, we use the modified timestamp and the assembly MVID, both of which you can look up and store with the cache in order to invalidate the cache when loading it.

**Comment by znakeeye** [comment]
Thanks. I decided to serialize the scanned assembly timestamps together with the graph data. If the timestamps differs, the cache is invalidated.

**Comment by AArnott** [comment]
Sounds good. FYI you can get a full list of all the assemblies that were included in the cache (which is more than the ones you passed in to be scanned, since it includes relevant reference assemblies) by calling the [`GetInputAssemblies`](https://github.com/microsoft/vs-mef/blob/54449a6267c96a0e247b176975b29b56168a0abe/src/Microsoft.VisualStudio.Composition/ComposableCatalog.cs#L154) method.

**Comment by znakeeye** [comment]
Brilliant! So that gives you the ability to check timestamps of assemblies e.g. in the GAC (that might have been updated)?

**Comment by AArnott** [comment]
Yes

**Comment by znakeeye** [comment]
The timestamp seems to be correct for all but `Nuget` assemblies, including `Microsoft.VisualStudio.Composition`:

> Microsoft.VisualStudio.Composition: 1904-03-23 04:08:04

Why do these DLLs have these weird timestamps? Are nuget packages built with the `/deterministic` flag?

**Comment by AArnott** [comment]
Yes, vs-mef assemblies are built with the deterministic flag.
When I said check timestamp, I wasn't talking about its internal timestamp. I was talking about the last write timestamp from the file system.

**Comment by znakeeye** [comment]
I realized that my timestamp check is very slow. Do you know when this type of timestamp check is absolutely necessary? I'm thinking that it might be enough to check the timestamp during development. But in production, what would happen if a Windows Update causes some serialized .NET dependencies to be updated?

Do you have any suggestion on how to determine when it is necessary to perform this check? E.g. A `Windows was updated` event or similar? Obviously, we want to avoid runtime errors at all cost!

Currently, I have this code for timestamp verification.

**Check timestamps when reading graph from disk.**
```c#
DateTime CreateTimestamp(AssemblyName assemblyName)
{
    var path = new Uri(assemblyName.CodeBase).LocalPath;
    return File.GetLastWriteTime(path); // This is slow!
}

// Then, after catalogManager.LoadAsync()...
var timestamps = LoadTimestamps(stream);
bool isValid = timestamps.SequenceEqual(catalog.GetInputAssemblies().Select(CreateTimestamp));
```

Another idea is to only check timestamps on our own assemblies, not anything from the system/GAC.

**Comment by AArnott** [comment]
VS-MEF can tolerate Windows Updates that touch .NET assemblies. It has a dual-path for cache scenarios: fast path and slow path. It uses fast path if the assemblies haven't changed at all since the cache was created, and it quietly falls back to the slow path if they have changed in order to avoid a runtime failure. 

In VS we have a complicated and tuned cache invalidation system that I hope to one day move into this repo to share with everyone. But it needn't be so complex if your app isn't extensible after it ships. If it's not extensible, I would use the AppHost package to build the cache on build and ship it, without worrying about invalidating the cache.

**Comment by znakeeye** [comment]
Great! Our app is not extensible for sure. So we should be safe if we put the timestamp check inside an `#if DEBUG` (for developing)?

We are considering creating the cache and ship it, but another possibility is to create it on load if it doesn't exist. That way we have a fallback. Only first execution would be a bit slower.

**Comment by AArnott** [comment]
I'm not sure why you would need it for `DEBUG`, if every time you build it will check and/or refresh the cache.

Yes, you could create it on startup if it's missing, and thus avoid shipping the cache file. I'm not sure there is much/any benefit to that, and you'd have more code to write and maintain.
If VS-MEF ever picks up more of the cache management features, it would certainly offer this option.

**Comment by znakeeye** [comment]
Thanks for your quick response.

In `DEBUG` a developer might add a new export, and the previously created cache will not include it. So that will confuse the developer.

Maybe I should add a custom buid step to delete the cache on Build.

I want developers to both benefit from the cache and allow them to add new exports without any hassle. Tricky!

**Comment by AArnott** [comment]
I agree. But the cache should be built on every build, so if the developer adds an Export, on the very next test run or debug launch they'll be running with the new cache.
