### ISSUE TITLE
How to "transfer" resolved instances from a container to another?

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#156]
I want to achieve the following.

1. On a worker thread, an `ExportProvider` resolves one single type and calls one method to retrieve data. E.g.:

```c#
var dataLoader = MiniContainer.GetExportedValue<IDataLoader>();
dataLoader.RetrieveData();
```

2. Meanwhile, on the UI thread, the app's `ExportProvider` resolves all exported types and values. I.e. regular bootstrapping.

3. When the main container is ready, I want to "transfer" the `IDataLoader` instance from the worker thread. That way, the main container can load super-fast.

**How can this be achieved?** I guess this operation would be equivalent to "as soon as type X is resolved, call X.Foo() in a worker thread, then wait for it after bootstrapping".

Please advise :)

**Comment by weltkante** [comment]
This is not solvable in general because

- The implementation of IDataLoader may depend on arbitrary other services in the container. Services can require sharing (singleton pattern), if you start merging graphs you could have overlaps (the same service was created in both containers) so now you have two instances of a service. Even if you were to resolve that, services could have been resolved to different implementations in different containers, which would make it impossible to reconcile in a general solution.

- Merging a service into a container could introduce new exports which would have to be retroactively fitted into already created instances.

What you are looking at is a form of runtime composition, I think the older MEF v1 had this, but it was dropped from later versions (not sure about v2 but I think it is gone there already). Anyways, the point of VSMEF is to have a static catalog which you can reason about, merging resolved services at runtime contradicts that design goal, so it was intentionally dropped as a feature as far as I understand.

(PS: I'm not related to the project, I'm just speaking from my background knowledge)

**Comment by znakeeye** [comment]
Thanks for clarification.

I guess I could accomplish what I want by transferring _data_ between two instances instead. E.g.:
```c#
var a = Container1.GetExportedValue<ILoader>();
a.LoadData();

var b = Container2.GetExportedValue<ILoader>();
b.SetPreLoadedData(a.GetData());
```

**Comment by weltkante** [comment]
That said, one way to solve it is to not put IDataLoader into the catalog at all. You can have an IDataLoaderProvider in the catalog which will do all the async background stuff, and when its done it publishes the IDataLoader. Everyone would import the IDataLoaderProvider and access the IDataLoader through it, and you can decide how to handle "early access" (eg. blocking, async/await etc.)

**Comment by znakeeye** [comment]
Interesting idea. Thanks!

**Comment by AArnott** [comment]
I don't understand why you would use two containers. One catalog and one container is thread-safe, so you can do all the fast stuff on the main thread while a background thread calls `GetExportedValue<IHeavyPart>` and just discards the result. Once the part has been activated on a background thread, all accesses to it in the future will be fast (assuming the part is Shared or otherwise fast to create multiple times).

**Comment by znakeeye** [comment]
Thanks @Aarnott. That is certainly a good solution. My hope, however, was to do heavy stuff (on an exported instance) while the container is built.

**Comment by AArnott** [comment]
If the container takes a long time to build, you would probably do well to use our cache support.

However, you *can* air-lift a value into the container. It just has to have an export for it before hand. See this doc: https://github.com/microsoft/vs-mef/blob/master/doc/dynamic_recomposition.md#adding-parts-directly-with-compositioncontainercompose

**Comment by znakeeye** [comment]
Won't you get multiple exports when air-lifting an export that is also exported by the scanned assemblies?

**Comment by AArnott** [comment]
I wouldn't air-lift it from an export. You said that the MEF container takes a long time to initialize. So I would just run whatever code is necessary to produce that value directly (no MEF), then set it on the exporting MEF property when it's ready.

That said, I can only see this helping you if you're going to do this in parallel to a long MEF container construction. Otherwise you could just let MEF do it within the primary container. And if MEF container construction takes a long time, I would use a cache. 
So I wouldn't actually use the solution regarding air-lifting at all. I only use the air-lifting technique to "export" values that come from another system that MEF cannot instantiate.

**Comment by znakeeye** [comment]
Ok. So the basic idea is to explicitly set the value of an export - preventing the framework from retrieving its value from reflected constructor? (When an import is realized.)

**Comment by AArnott** [comment]
> So the basic idea is to explicitly set the value of an export

Explicitly set the value on an exporting *property*, yes. After which, any access to that property *getter* will of course return the value you set it to. That means when MEF accesses that property to get its exported value, it will get the value you set it to.
It also means that if MEF accesses that property *before* you set it, MEF will get the default value instead and assign that to the importer that wanted it. This is the huge limitation of this air-lifting technique. You'd have to be very careful to not activate any MEF part that imports this value until the export has been set.

> preventing the framework from retrieving its value from reflected constructor?

I don't know what you mean by this. You're not preventing the framework from anything.
