### ISSUE TITLE
GC pressure in CompositionConfiguration even when loading from cache

### ISSUE THREAD

**Issue by znakeeye** [microsoft/vs-mef#172]
Targeting .NET Framework **4.7.2**. First of all, I don't understand why I see this when loading the MEF graph from disk. Why does it try to find loops when the deserialized graph obviously cannot have any loops?

I see lots of temporary allocations at
[CompositionConfiguration.cs(297)](https://github.com/microsoft/vs-mef/blob/master/src/Microsoft.VisualStudio.Composition/CompositionConfiguration.cs#L297). It's like 100 MB of `Enumerable.Where<T>` that is thrown away, causing unwanted memory pressure.

I believe this can be optimized. I.e. don't use LINQ, no matter what. If I find time, I'll try to help out.

![vs-mef-gc](https://user-images.githubusercontent.com/958469/71727123-9a012000-2e39-11ea-9ae1-bc74e775517d.png)

**Comment by AArnott** [comment]
`FindLoops` *isn't* called when loading a *graph* from the cache. It's only called from `CompositionConfiguration.Create(catalog)`. So you might have cached the catalog, but you're creating the graph at runtime, and that's when loops must be detected.
If you actually cache the graph itself, it wouldn't execute this code.

Regarding the GC pressure, I see exactly one use of the `Where` extension method. We might be able to replace this in order to avoid some allocations. But if you meant to be caching the graph and can fix that, the cost of creating the graph will entirely go away.

**Comment by znakeeye** [comment]
You're right. The cache is loaded using `catalogManager.LoadAsync()` and then this `CompositionConfiguration.Create()` API is called. I guess I need to re-work my caching mechanism to avoid this when loading from cache.

**Comment by AArnott** [comment]
Use the `CachedComposition` class [here](https://github.com/microsoft/vs-mef/blob/master/src/Microsoft.VisualStudio.Composition/Configuration/CachedComposition.cs) to cache the graph itself.

**Comment by znakeeye** [comment]
This will certainly improve startup performance in our app. Thanks for that link!

Still, I think you should get rid of those `Where` and `Select` calls. Together they account for 200 MB allocations in our huge app.

**Comment by AArnott** [comment]
> Together they account for 200 MB allocations in our huge app.

I doubt that. I think you're misattributing all the code that runs in the delegates to the use of `Where` and `Select` directly. If we removed use of those extension methods we'd still need to run the code in the delegates, so almost all those allocations would still occur.

**Comment by znakeeye** [comment]
Possibly. But a million enumerator allocations would certainly be of importance. We have an enormous amount of exports and imports.
